apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: ticket-service
    tier: database
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: ticket-service
    tier: database
