apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: ticket-service
    tier: backend
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: ticket-service
    tier: backend
