apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: ticket-service-web
      tier: frontend
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: ticket-service-web
        tier: frontend
    spec:
      containers:
      - name: ticket-service-web
        image: registry.digitalocean.com/biggestfan/ticket/ticket-sales-web:21.08.1-hotfix-1-11-g09186da
        resources:
          requests:
            cpu: 300m
            memory: 300Mi
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: biggestfan-registry
