apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: ticket-sales-web
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: ticket-sales-web
        tier: frontend
    spec:
      containers:
      - name: ticket-sales-web
        image: registry.digitalocean.com/biggestfan/ticket/ticket-sales-web:21.08.1-hotfix-1-11-g09186da
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
